dist: trusty

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install @angular/cli

script:
  - ng build --prod
  - cp dist/braydonharris/index.html dist/braydonharris/404.html
  - 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/braydonharris
  on:
    branch: master
