dist: trusty

language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  - npm install
  - npm install @angular/cli

script:
  - ng build --prod --base-href https://invaderb.github.io/