# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Angular Full CI
      uses: colbyhill21/angular-full-ci@v1.0
      with:
        # Command to run tests on your project, do not prepend with "npm", it is already included.
        testcommand: test
        
    - name: Publish to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        # The name of the directory that containing the content to be published
        dir: /dist/braydonharris
        # The name of the remote branch that publishing source for GitHub Pages site
        #branch: # optional, default is gh-pages
        # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
        #repo: # optional
        # The personal access token that authorize repo access
        #token: 
